<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>WinExe</OutputType><TargetFramework>net8.0-windows</TargetFramework><UseWindowsForms>true</UseWindowsForms><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><AssemblyName>AMZG</AssemblyName><Version>0.8.1</Version></PropertyGroup><ItemGroup><ProjectReference Include="..\AMZG.Core\AMZG.Core.csproj" /></ItemGroup></Project>