using System.Diagnostics;
using System.IO.Compression;
using System.Net.Http.Json;
namespace AMZG.Core;
public sealed record UpdateManifest(string Version,string PackageUrl,string Sha256,bool Mandatory,string[]? Modules,string? Notes);
public static class AutomaticUpdater {
 public const string CurrentVersion="0.8.1";
 public const string ManifestUrl="https://raw.githubusercontent.com/giliotiesg-pixel/erp-gratidao-updates/main/amzg-manifest.json";
 static readonly HttpClient Http=new(){Timeout=TimeSpan.FromMinutes(5)};
 public static async Task<UpdateManifest?> CheckAsync(CancellationToken ct=default){try{var m=await Http.GetFromJsonAsync<UpdateManifest>(ManifestUrl,ct);if(m is null||!Version.TryParse(m.Version,out var remote)||!Version.TryParse(CurrentVersion,out var local)||remote<=local)return null;if(string.IsNullOrWhiteSpace(m.PackageUrl)||string.IsNullOrWhiteSpace(m.Sha256)||m.Sha256.Length!=64)return null;return m;}catch{return null;}}
 public static async Task<string> DownloadAndValidateAsync(UpdateManifest m,IProgress<int>? progress=null,CancellationToken ct=default){SafeStorage.Ensure();var dst=Path.Combine(SafeStorage.UpdateRoot,$"AMZG-{m.Version}.zip");using var resp=await Http.GetAsync(m.PackageUrl,HttpCompletionOption.ResponseHeadersRead,ct);resp.EnsureSuccessStatusCode();var len=resp.Content.Headers.ContentLength??-1;await using var input=await resp.Content.ReadAsStreamAsync(ct);await using var output=File.Create(dst);var buf=new byte[81920];long total=0;int n;while((n=await input.ReadAsync(buf,ct))>0){await output.WriteAsync(buf.AsMemory(0,n),ct);total+=n;if(len>0)progress?.Report((int)(total*100/len));}await output.FlushAsync(ct);if(!string.Equals(SafeStorage.Sha256(dst),m.Sha256,StringComparison.OrdinalIgnoreCase)){File.Delete(dst);throw new InvalidDataException("SHA-256 da atualização é inválido.");}using var zip=ZipFile.OpenRead(dst);if(zip.Entries.Any(e=>new[]{".db",".sqlite",".sqlite3"}.Contains(Path.GetExtension(e.FullName),StringComparer.OrdinalIgnoreCase))){File.Delete(dst);throw new InvalidDataException("Pacote contém banco de dados e foi bloqueado.");}return dst;}
 public static void ApplyAndRestart(string zip){var maint=Path.Combine(AppContext.BaseDirectory,"AMZG.Maintenance.exe");if(!File.Exists(maint))throw new FileNotFoundException("AMZG.Maintenance.exe não encontrado.",maint);Process.Start(new ProcessStartInfo(maint,$"--apply-update \"{zip}\" {Environment.ProcessId}"){UseShellExecute=true,Verb="runas"});Environment.Exit(0);}
}