package main

import "fmt"

func salesSummary12115(from,to string)([][]string,error){w:="status='CONCLUIDA'";if from!=""{w+=" AND date(created_at)>=date('"+esc(from)+"')"};if to!=""{w+=" AND date(created_at)<=date('"+esc(to)+"')"};q:="SELECT date(created_at),COUNT(*),printf('%.2f',SUM(total)),printf('%.2f',SUM(cost_total)),printf('%.2f',SUM(profit)),printf('%.2f',SUM(tithe_due)) FROM sales WHERE "+w+" GROUP BY date(created_at) ORDER BY date(created_at) DESC";return queryRows(q,6)}
func topProducts12115(month string)([][]string,error){w:="s.status='CONCLUIDA'";if month!=""{w+=" AND strftime('%Y-%m',s.created_at)='"+esc(month)+"'"};return queryRows("SELECT si.product_description_snapshot,printf('%.3f',SUM(si.qty)),printf('%.2f',SUM(si.line_total)) FROM sale_items si JOIN sales s ON s.id=si.sale_id WHERE "+w+" GROUP BY si.product_description_snapshot ORDER BY SUM(si.qty) DESC LIMIT 50",3)}
func profitSummary12115(from,to string)(map[string]string,error){w:="status='CONCLUIDA'";if from!=""{w+=fmt.Sprintf(" AND date(created_at)>=date('%s')",esc(from))};if to!=""{w+=fmt.Sprintf(" AND date(created_at)<=date('%s')",esc(to))};rows,e:=queryRows("SELECT printf('%.2f',COALESCE(SUM(total),0)),printf('%.2f',COALESCE(SUM(cost_total),0)),printf('%.2f',COALESCE(SUM(profit),0)),printf('%.2f',COALESCE(SUM(tithe_due),0)) FROM sales WHERE "+w,4);if e!=nil||len(rows)==0{return nil,e};return map[string]string{"faturamento":rows[0][0],"custo":rows[0][1],"lucro":rows[0][2],"dizimo":rows[0][3]},nil}
func lowStockReport12115()([][]string,error){return queryRows("SELECT id,COALESCE(barcode,''),description,printf('%.3f',stock),printf('%.3f',min_stock),COALESCE(expiration_date,'') FROM products WHERE active=1 AND stock<=min_stock ORDER BY stock ASC,description",6)}
func validityReport12115(days int)([][]string,error){if days<=0{days=30};return queryRows(fmt.Sprintf("SELECT id,COALESCE(barcode,''),description,COALESCE(expiration_date,''),printf('%%.3f',stock) FROM products WHERE expiration_date IS NOT NULL AND expiration_date<>'' AND date(expiration_date)<=date('now','+%d day') ORDER BY date(expiration_date)",days),5)}
